chore: fix failed piplines (#66)
* chore: fixed typo in replication-job

* added verify that repo exists

diff --git a/.github/workflows/replicate-used-images.yaml b/.github/workflows/replicate-used-images.yaml
--- a/.github/workflows/replicate-used-images.yaml
+++ b/.github/workflows/replicate-used-images.yaml
@@ -60,6 +60,7 @@ jobs:
             docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{ matrix.region }}.amazonaws.com
 
       - name: Run ECR cache script
+        shell: bash
         run: |
           helm dep build ./charts/kompass
           SOURCE_REGION="eu-west-1"
@@ -122,7 +123,26 @@ jobs:
               fi
 
               if echo "$registry" | grep -q "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr"; then
+                  DEST_REPO="$name_and_prefix"
+                  DEST_REGION="${{ matrix.region }}"
+                  ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"
+
+                  # Check if the destination repository exists
+                  if ! aws ecr describe-repositories \
+                      --region "$DEST_REGION" \
+                      --repository-names "$DEST_REPO" \
+                      --output text >/dev/null 2>&1; then
+                      echo "🔧 Destination repository '$DEST_REPO' not found in region $DEST_REGION. Creating..."
+                      aws ecr create-repository \
+                          --region "$DEST_REGION" \
+                          --repository-name "$DEST_REPO" \
+                          --image-scanning-configuration scanOnPush=true \
+                          --encryption-configuration encryptionType=AES256
+                  else
+                      echo "✅ Destination repository '$DEST_REPO' exists in region $DEST_REGION"
+                  fi
                   echo "🟡 ECR image detected, replicating from $SOURCE_REGION"
+
                   skopeo copy -a --src-creds AWS:$(aws ecr get-login-password --region $SOURCE_REGION) \
                               --dest-creds AWS:$(aws ecr get-login-password --region ${{ matrix.region }}) \
                               docker://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$SOURCE_REGION.amazonaws.com/$name_and_prefix:$tag \
